const JOIN_ROOM = 'JOIN_ROOM';
const USER_JOINED_ROOM = 'USER_JOINED_ROOM';
const USER_LEAVE_ROOM = 'USER_LEAVE_ROOM';
const USER_LIST = 'USER_LIST';
const SEND_MESSAGE = 'SEND_MESSAGE';
const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
const SET_NICKNAME = 'SET_NICKNAME';
const REMOVE_LAST_MESSAGE = 'REMOVE_LAST_MESSAGE';
const TYPING = 'TYPING';
const OTHER_IS_TYPING = 'OTHER_IS_TYPING';

module.exports = {
    JOIN_ROOM,
    USER_JOINED_ROOM,
    USER_LEAVE_ROOM,
    USER_LIST,
    SEND_MESSAGE,
    RECEIVE_MESSAGE,
    SET_NICKNAME,
    REMOVE_LAST_MESSAGE,
    TYPING,
    OTHER_IS_TYPING,
}
